[package]
name = "cb-rs"
version = "0.1.0"
authors = ["Chance <albatross@loftwing.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.98", features = ["derive"]}
serde_json =  "1.0.40"
reqwest = "0.9.19"
log = "*"
env_logger = "*"
